export const workProjects = [
  {
    id: 'leafcrm',
    title: 'Leaf CRM',
    subtitle: 'Multi-Tenant Lead Management Platform',
    url: 'https://leafcrm.com',
    role: 'Backend Developer (Full Stack)',
    description: 'A comprehensive SaaS lead management system designed for businesses that generate leads through digital marketing channels. The platform enables organizations to capture, assign, and track leads from multiple sources while providing real-time analytics and team collaboration features.',
    screenshot: '/images/work/leafcrm-screenshot.webp',
    keyContributions: [
      "Integrated third-party lead sources including Facebook, Google, TikTok, and WordPress forms",
      "Built webhook endpoints and API authentication flows for external lead integrations",
      "Implemented automatic lead assignment logic",
      "Applied security best practices based on OWASP Top 10 and SANS 25",
      "Built report export features and visual reporting dashboards",
      "Developed secure APIs with token-based authentication and response transformers",
      "Developed backend admin features for tenant, user, role, and system configuration management"
    ],
    integrations: [
      'Facebook Lead Ads',
      'Google Ads',
      'TikTok Lead Generation',
      'Email Marketing Platforms',
      'Cloud Storage (AWS S3, SFTP)',
      'Webhook APIs',
    ],
    techStack: [
      'Laravel',
      'PHP',
      'MySQL',
      'Redis',
      'Bootstrap',
      'JavaScript',
    ],
  },
  {
    id: 'claimnow',
    title: 'ClaimNow',
    subtitle: 'AI-Powered Contest Management System',
    url: 'https://claim.my',
    role: 'Backend Developer (AI Integration & Analytics)',
    description: 'A multi-tenant SaaS platform that streamlines promotional claims processing through AI automation. The system handles end-to-end claim submission, validation, and fulfillment workflows.',
    screenshot: '/images/work/claimnow-screenshot.webp',
    keyContributions: [
      'AI-powered chatbot integration with messaging platforms',
      'Multi-language support for customer interactions',
      'Analytics dashboard for cost tracking and usage monitoring',
      'Intelligent conversation management system',
      'Customer support interface with live chat capabilities',
    ],
    integrations: [
      'WhatsApp Cloud API',
      'OpenAI API (ChatGPT)',
      'Google Gemini',
      'Google Vision OCR',
      'Microsoft Teams',
      'Firebase',
      'Cloud Storage',
    ],
    techStack: [
      'Laravel',
      'PHP',
      'MySQL',
      'PostgreSQL',
      'Redis',
      'OpenAI API',
      'Bootstrap',
      'JavaScript',
    ],
  },
];
