export const workProjects = [
  {
    id: 'leafcrm',
    title: 'Leaf CRM',
    subtitle: 'Multi-Tenant Lead Management Platform',
    url: 'https://leafcrm.com',
    role: 'Backend Developer (Full Stack)',
    description: 'A multi-tenant SaaS platform for capturing, assigning, and tracking leads from digital marketing channels with real-time analytics.',
    screenshot: '/images/work/leafcrm-screenshot.webp',
    keyContributions: [
      "Integrated third-party lead sources (Facebook, Google, TikTok, WordPress)",
      "Built APIs and webhooks for external integrations and mobile app",
      "Applied OWASP Top 10 and SANS 25 security best practices",
      "Developed reporting dashboards with export capabilities",
      "Built admin features for multi-tenant configuration management"
    ],
    integrations: [
      'Facebook Lead Ads',
      'Google Ads',
      'TikTok Lead Generation',
      'Email Marketing Platforms',
      'AWS S3',
    ],
    techStack: [
      'Laravel',
      'PHP',
      'MySQL',
      'Redis',
      'JavaScript',
    ],
    timeline: "Mar 2019 - Present",
  },
  {
    id: 'claimnow',
    title: 'ClaimNow',
    subtitle: 'AI-Powered Contest Management System',
    url: 'https://claim.my',
    role: 'Backend Developer (AI Integration & Analytics)',
    description: 'A multi-tenant SaaS platform that streamlines promotional claims processing through AI automation. The system handles end-to-end claim submission, validation, and fulfillment workflows.',
    screenshot: '/images/work/claimnow-screenshot.webp',
    keyContributions: [
      'AI-powered chatbot integration with messaging platforms',
      'Multi-language support for customer interactions',
      'Analytics dashboard for cost tracking and usage monitoring',
      'Intelligent conversation management system',
      'Customer support interface with live chat capabilities',
    ],
    integrations: [
      'WhatsApp Cloud API',
      'OpenAI',
      'Google Gemini',
      'Google Vision OCR',
      'AWS S3',
    ],
    techStack: [
      'Laravel',
      'PHP',
      'MySQL',
      'PostgreSQL',
      'Redis',
      'JavaScript',
    ],
    timeline: "Jun 2024 - Present",
  },
];
